name: luhn

dependencies:
  - base

ghc-options:
  - -Wall

library:
  source-dirs: src

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
    - luhn

tests:
  spec:
    source-dirs: test
    main: Main.hs
    dependencies:
      - hspec
      - luhn
