name: komatsu

dependencies:
  - base

ghc-options:
  - -Wall

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Main.hs
    dependencies:
      - QuickCheck
      - hspec
      - komatsu
